module.exports = [
   {
      id: 1,
      nome: 'Uma Mão',
      tipo: 'ataque físico',
      descricao: 'Melhoria de habilidades com armas físicas de uma mão.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 2,
      nome: 'Escudo',
      tipo: 'defesa física',
      descricao: 'Melhora habilidades de bloqueio, auxiliando a defesa.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 3,
      nome: 'Destruição',
      tipo: 'ataque mágico',
      descricao: 'Potencializa feitiços de dano, melhorando o poder e efeitos dos feitiços.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 4,
      nome: 'Alteração',
      tipo: 'defesa mágica',
      descricao: 'Auxilia na defesa mágica, alterando itens e equipamentos durante a batalha.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 5,
      nome: 'Arquearia',
      tipo: 'ataque físico',
      descricao: 'Melhora o dano, alcance e precisão com arcos e bestas',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 6,
      nome: 'Furtividade',
      tipo: 'furtividade',
      descricao: 'Auxilia na fuga e camuflagem, ajudando a passar despercebido ou despistar inimigos se escondendo em plena vista.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   },
   {
      id: 7,
      nome: 'Alquimia',
      tipo: 'poções',
      descricao: 'Melhora as chances na criação de uma poção, bem como seu poder e efeitos.',
      level: 1,
      exp: 0,
      proxLevel: 100,
   }
]